@startuml
'https://plantuml.com/activity-diagram-beta

start
:Check if n < 0?;
if (yes) then (true)
  :Throw IllegalArgumentException;
else (no)
  :Check if n <= 1?;
  if (yes) then (true)
    :Return n;
  else (no)
    :Return fibonacci(n - 1) + fibonacci(n - 2);
  endif
endif
stop
@enduml
